# EXAMPLE ONLY
# Simple nginx router to show how you can access wallet endpoints from a specific
# API domain (instead of specifying the port #)
# Alertnatively you can access wallet with bcoin.yourdomain.org:8334 (mainnet)
# Without using this configuration

version: '2'
services:
  bcoin-wallet:
    image: smebberson/alpine-nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: bwallet.yourdomain.org
      CERT_NAME: purse.io
    volumes:
      - ./wallet-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    networks:
      - "bcoin"
      - "nginx-proxy"

networks:
  bcoin:
    external:
      name: "bcoin"
  nginx-proxy:
    external:
      name: "nginx-proxy"
