version: '2'

services:
  bcoin:
    image: purse/bcoin
    container_name: bcoin
    restart: unless-stopped
    ports:
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC/HTTP
      - "8334:8334" # Wallet
      #-- Testnet
      #- "18333:18333"
      #- "18332:18332" # RPC/HTTP
      #- "18334:18334"
    environment:
      BCOIN_CONFIG: /data/bcoin.conf
      VIRTUAL_HOST: bcoin.yourdomain.org
      VIRTUAL_PORT: 8332
      #VIRTUAL_PORT: 18332 # Testnest
    networks:
      - "bcoin"
      - "nginx-proxy"
    volumes:
      - ~/.bcoin:/data
      - ${PWD}/secrets/bcoin.conf:/data/bcoin.conf
      - ${PWD}/secrets/wallet.conf:/data/wallet.conf

  # EXAMPLE ONLY
  # Simple nginx router to show how you can access wallet endpoints from a specific
  # API domain (instead of specifying the port #)
  # Alertnatively you can access wallet with bcoin.yourdomain.org:8334 (mainnet)
  bcoin-wallet:
    image: smebberson/alpine-nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: bwallet.yourdomain.org
      CERT_NAME: purse.io
    volumes:
      - ./wallet-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    networks:
      - "bcoin"
      - "nginx-proxy"

  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "nginx-proxy"
    volumes:
      - ./secrets/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  bcoin:
    external:
      name: "bcoin"
  nginx-proxy:
    external:
      name: "nginx-proxy"
